apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: free5gc-gitrepo
  namespace: flux-system
spec:
  interval: 10s
  url: https://github.com/varun-chandramouli/ios-mcn-core-helm-chart
  ref:
    branch: iosmcnmaster
  secretRef:
    name: free5gc-github-auth
  ignore: |
    # exclude all
    /*
    # include charts dir
    !/charts
